#!/bin/bash
#this short script checks the data/imglist file and ensures there are no duplicate lines or nonexistent files.

DIRECTORY="$(dirname "$(dirname $0)")"

echo "$(find "$HOME" -maxdepth 1 -name "*.img" )" >> "${DIRECTORY}/data/imglist"
echo "$(find "$HOME/Downloads" -maxdepth 1 -name "*.img")" >> "${DIRECTORY}/data/imglist"

mkdir -p "${DIRECTORY}/data"

#if imglist exists, ensure all lines contain valid files
if [ -f "${DIRECTORY}/data/imglist" ];then #if imglist exists
  #number of lines in file
  numlines=$(wc -l "${DIRECTORY}/data/imglist" | awk '{ print $1 }')
  #echo $numlines
  if [ $numlines -gt 0 ];then #if imglist contains any lines
    echo "$(sort "${DIRECTORY}/data/imglist" | uniq)" > "${DIRECTORY}/data/imglist" #remove duplicate lines
    i=1
    while [ $i -le $numlines ]; do #repeat until all lines are checked
      line=$(sed -n "${i}p" < "${DIRECTORY}/data/imglist") #read that line of text file
      #echo $line
      if [ ! -f $line ];then #if line is file not found
        #echo "not exist!"
        sed -i "${i}d" "${DIRECTORY}/data/imglist" #delete the line
      fi
      i=$((i+1)) #increase line number by 1 to check the next one
    done
    imglist="$(cat ${DIRECTORY}/data/imglist | tr '\n' '!')"
  fi
else
  #create file
  echo '' > "${DIRECTORY}/data/imglist"
  exit 1
fi
if [ ! -z "$imglist" ];then
  imglist="${imglist::-1}"
fi
echo "$imglist" #this is the output of the script
