#!/bin/bash

#$1 is image file path
#$2 is additional MB

imagefile=$1

if [ -z $2 ];then
  addmb=0
else
  addmb=$2
fi

oops(){
  echo -e "\n\e[41m${1}\e[49m\n"
  exit 1
}

warn(){
  echo -e "\nBeware: \e[31m${1}\e[39m\n"
}

if [ "$addmb" -lt 0 ];then
  oops 'Cannot have a negative additional megabyte!'
fi

loopdev="$(sudo losetup -fP --show "$imagefile")"
function cleanup {
  sudo losetup -d $loopdev || warn 'Failed to delete loop device!'
}

trap cleanup EXIT

#loopdev=/dev/loop0
echo "loop: $loopdev"

partpath="${loopdev}p2"
if [ ! -b $partpath ];then
  oops 'Partition 2 does not exist.'
fi

sudo e2fsck -f $partpath || warn 'Check filesystem failed.'

#shrink filesystem
echo '
shrinking filesystem'
sudo resize2fs -M $partpath || oops 'Shrink filesystem failed.'

fsend="$(sudo resize2fs -P $partpath | awk 'NF>1{print $NF}')"
echo "endblock: ${fsend}"

partstart="$(sudo fdisk -l $loopdev | grep $partpath | awk '{print $2}')"
echo "partition start: ${partstart}"

#ensure partition start is valid
if [ $partstart -gt '500000' ];then
  true
  #partend must be valid
else
  oops 'Could not locate start of partition!'
fi

echo '
shrinking partition'
# ---pretend-input-tty is an undocumented feature. See https://unix.stackexchange.com/a/365657/369481
echo "y
i
i
2
$((fsend*4096+(partstart-1)*512))b
y" | sudo parted $loopdev ---pretend-input-tty resizepart 2 $((fsend*4096+(partstart-1)*512))b || oops "failed to shrink partition."

echo '
refreshing loop device'
sudo losetup -d $loopdev || warn 'refreshing failed on step 1.'
loopdev="$(sudo losetup -fP --show "$imagefile" || oops 'refreshing failed on step 2.')"

partend="$(sudo fdisk -l $loopdev | grep $partpath | awk '{print $3}')"
echo "partition end: ${partend}"

#ensure partition end is valid
if [ $partend -gt '300000' ];then
  true
  #partend must be valid
else
  oops 'Could not locate end of partition!'
fi

#chop off unused portion of image file
echo '
removing unused portion of file'
truncate -s $(((partend+1)*512+(addmb)*1038*1024)) "$imagefile" || oops 'extend img failed.'

echo '
refreshing loop device'
sudo losetup -d $loopdev || warn 'refreshing failed on step 1.'
loopdev="$(sudo losetup -fP --show "$imagefile" || oops 'refreshing failed on step 2.')"

#extend partition to eof
echo '
extending partition to eof'
echo y | sudo parted $loopdev ---pretend-input-tty resizepart 2 100% || warn 'partition extension failed.'

echo '
refreshing loop device'
sudo losetup -d $loopdev || warn 'refreshing failed on step 1.'
loopdev="$(sudo losetup -fP --show "$imagefile" || oops 'refreshing failed on step 2.')"

#expand filesystem
echo '
expanding filesystem'
sudo resize2fs $partpath || warn 'filesystem expansion failed.'

echo '
final filesystem check'
sudo e2fsck -f -p $partpath || warn 'check filesystem failed.'

#open to check
#sudo gparted $loopdev

#The cleanup function deletes the loopdev
