#!/bin/bash

DIRECTORY="$(dirname "$(dirname $0)")"

LOOP="$(sudo losetup -fP --show "$1")"
trap "sudo losetup -d $LOOP" EXIT

sudo "${DIRECTORY}/functions/zerofree" -v "${LOOP}p2" || exit 1

sudo "${DIRECTORY}/functions/image-shrink" "$1"